### ISSUE TITLE
The "polyfill" config doesn`t wrok

### ISSUE THREAD

**Issue by jarbinup** [modern-js-dev/modern-js-examples#15]
My config is :

```json
"output": {
      "enableModernMode": true,
      "polyfill": "ua"
 }
```

 https://github.com/jarbinup/remote/blob/main/hello-morden-auto/package.json#L58
 
![image](https://user-images.githubusercontent.com/13498074/146089759-fc2c91cf-d659-4fb1-94f2-1013d22f5bab.png)

 
<img width="1399" alt="WechatIMG421" src="https://user-images.githubusercontent.com/13498074/146090874-628e1b1e-723f-454f-8efa-2acb7cc46a53.png">

**Comment by zllkjc** [comment]
add @modern-js/plugin-polyfill to dependencies, then install and try again..we will fix this bug next version
