### ISSUE TITLE
Module not found: path argument is not a string

### ISSUE THREAD

**Issue by alizhang** [modern-js-dev/modern-js-examples#16]
Failed to compile.

./node_modules/.pnpm/registry.npmmirror.com+antd@4.18.3_react-dom@17.0.2+react@17.0.2/node_modules/antd/es/empty/style/index.js
Module not found: path argument is not a string

Node: v16.13.2
Npm: 8.1.2
webpack: 5.66.0
webpack-cli: 4.9.1

**Comment by alizhang** [comment]
import './App.css' cause this bug, it seems that webpack loader does not work properly, not sure where can I update the config?

**Comment by caohuilin** [comment]
这个问题是由于 mini-css-extract-plugin break change 造成的，已修复
相关 issue：https://github.com/webpack-contrib/mini-css-extract-plugin/issues/896
